name: Deploy to shopify repo
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    build:
        name: Build and Commit
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              with:
                  ref: ${{ github.head_ref }}

            - name: Setup Node.js environment 🛎️
              uses: actions/setup-node@v3.8.1
              with:
                  node-version: '18.7.0'

            - name: Install pnpm 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
              run: |
                  npm install -g pnpm
                  pnpm install

            - name: Pushes to another repository
              uses: cpina/github-action-push-to-another-repository@main
              env:
                  SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
                  API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
              with:
                  source-directory: 'themes/venture'
                  destination-github-username: 'gbtunney'
                  destination-repository-name: 'pyromancy-shop-shopify'
                  user-email: gbtunney@mac.com
                  target-branch: development
                  create-target-branch-if-needed: true
